name: Build frontend
on:
  release:
    types:
      - published

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 7
      - name: Install dependencies
        working-directory: web
        run: pnpm install
      - name: Build
        working-directory: web
        run: pnpm run build
      - name: Archive
        run: zip -r fe-production.zip web/dist
      - name: Upload to release
        uses: svenstaro/upload-release-action@2.5.0
        with:
          file: fe-production.zip
          overwrite: true
          tag: ${{ github.event.release.tag_name }}

  umd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 7
      - name: Install dependencies
        working-directory: web
        run: pnpm install
      - name: Build
        working-directory: web
        run: pnpm run umd
      - name: Archive
        run: zip -r fe-umd.zip web/dist
      - name: Upload to release
        uses: svenstaro/upload-release-action@2.5.0
        with:
          file: fe-umd.zip
          overwrite: true
          tag: ${{ github.event.release.tag_name }}

